# Generated by Django 5.2.17 on 2026-10-04 09:30

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=100, verbose_name='họ và tên')),
                ('phone_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^0\\d{9}$', 'Số điện thoại phải gồm 10 chữ số và bắt đầu bằng 0.')], verbose_name='số điện thoại')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('email_verified', models.BooleanField(default=False, verbose_name='đã xác thực email')),
                ('role', models.CharField(choices=[('citizen', 'Người dân'), ('rescue_team', 'Đội cứu hộ'), ('admin', 'Admin')], db_index=True, default='citizen', max_length=20, verbose_name='vai trò')),
                ('address_detail', models.CharField(blank=True, max_length=255, verbose_name='số nhà, thôn/tổ')),
                ('home_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='vĩ độ nhà')),
                ('home_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='kinh độ nhà')),
                ('relative_phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^0\\d{9}$', 'Số điện thoại phải gồm 10 chữ số và bắt đầu bằng 0.')], verbose_name='số điện thoại người thân')),
                ('notify_in_app', models.BooleanField(default=True, verbose_name='nhận thông báo trên website')),
                ('notify_email', models.BooleanField(default=True, verbose_name='nhận thông báo qua email')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='đồng ý điều khoản lúc')),
                ('is_active', models.BooleanField(default=True, help_text='Bỏ chọn để khoá tài khoản.', verbose_name='đang hoạt động')),
                ('is_staff', models.BooleanField(default=False, verbose_name='vào được trang Django admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ngày tạo')),
                ('token_version', models.PositiveIntegerField(default=0, editable=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('rescue_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='catalog.rescueteam', verbose_name='đội cứu hộ')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='catalog.ward', verbose_name='phường/xã nơi ở')),
            ],
            options={
                'verbose_name': 'người dùng',
                'verbose_name_plural': 'người dùng',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('verify_email', 'Xác thực email'), ('reset_password', 'Đặt lại mật khẩu')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_user_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('rescue_team__isnull', True), ('role', 'rescue_team'), _connector='OR'), name='rescue_team_only_for_rescue_role'),
        ),
    ]
