# Generated by Django 5.2.17 on 2026-10-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('watch', 'Theo dõi'), ('warning', 'Cảnh báo'), ('emergency', 'Khẩn cấp')], max_length=10, verbose_name='mức')),
                ('source', models.CharField(choices=[('auto', 'Tự động'), ('manual', 'Thủ công')], default='auto', max_length=10, verbose_name='nguồn')),
                ('content', models.TextField(verbose_name='nội dung')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='bắt đầu')),
                ('valid_until', models.DateTimeField(verbose_name='hiệu lực đến')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='kết thúc lúc')),
                ('is_simulation', models.BooleanField(db_index=True, default=False, verbose_name='mô phỏng')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='thông báo gần nhất (giờ số liệu)')),
            ],
            options={
                'verbose_name': 'cảnh báo',
                'verbose_name_plural': 'cảnh báo',
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_simulation', models.BooleanField(default=False, verbose_name='mô phỏng')),
                ('level', models.CharField(choices=[('normal', 'Bình thường'), ('watch', 'Theo dõi'), ('warning', 'Cảnh báo'), ('emergency', 'Khẩn cấp')], default='normal', max_length=10, verbose_name='mức')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='xét đến giờ')),
            ],
            options={
                'verbose_name': 'trạng thái cảnh báo tự động',
                'verbose_name_plural': 'trạng thái cảnh báo tự động',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('web', 'Website'), ('email', 'Email')], max_length=10, verbose_name='kênh')),
                ('content', models.TextField(verbose_name='nội dung')),
                ('is_reminder', models.BooleanField(default=False, verbose_name='nhắc lại')),
                ('sent', models.BooleanField(default=False, verbose_name='đã gửi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='tạo lúc')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='đã xem lúc')),
            ],
            options={
                'verbose_name': 'thông báo',
                'verbose_name_plural': 'thông báo',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
