# Generated by Django 5.2.17 on 2026-10-08 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('reservoirs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='forecast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='reservoirs.forecast', verbose_name='kết quả dự báo'),
        ),
        migrations.AddField(
            model_name='alert',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='người phát'),
        ),
        migrations.AddField(
            model_name='alert',
            name='reservoirs',
            field=models.ManyToManyField(related_name='alerts', to='reservoirs.reservoir', verbose_name='hồ liên quan'),
        ),
        migrations.AddField(
            model_name='alert',
            name='wards',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='catalog.ward', verbose_name='phường/xã ảnh hưởng'),
        ),
        migrations.AddField(
            model_name='alertstate',
            name='reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservoirs.reservoir', verbose_name='hồ'),
        ),
        migrations.AddField(
            model_name='notification',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert', verbose_name='cảnh báo'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='người nhận'),
        ),
        migrations.AddConstraint(
            model_name='alertstate',
            constraint=models.UniqueConstraint(fields=('reservoir', 'is_simulation'), name='uniq_alert_state'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'channel', 'seen_at'], name='alerts_noti_recipie_0712ef_idx'),
        ),
    ]
