# Generated by Django 5.2.17 on 2026-10-04 09:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RescueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='tên đội')),
                ('phone_number', models.CharField(max_length=15, verbose_name='số điện thoại')),
                ('vehicles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('rescue_truck', 'Xe cứu hộ'), ('motorbike', 'Xe máy'), ('boat', 'Ca nô')], max_length=20), blank=True, default=list, size=None, verbose_name='phương tiện')),
            ],
            options={
                'verbose_name': 'đội cứu hộ',
                'verbose_name_plural': 'đội cứu hộ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='tên')),
                ('kind', models.CharField(choices=[('ward', 'Phường'), ('commune', 'Xã'), ('special_zone', 'Đặc khu')], max_length=20, verbose_name='loại')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='kinh độ')),
                ('priority', models.PositiveSmallIntegerField(default=100, verbose_name='thứ tự ưu tiên')),
            ],
            options={
                'verbose_name': 'phường/xã',
                'verbose_name_plural': 'phường/xã',
                'ordering': ['priority', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='uniq_ward_kind_name')],
            },
        ),
    ]
