# Generated by Django 5.2.17 on 2026-10-08 15:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='mã')),
                ('model_key', models.CharField(max_length=20, unique=True, verbose_name='khoá trong module dự báo')),
                ('name', models.CharField(max_length=100, verbose_name='tên hồ')),
                ('normal_water_level', models.FloatField(verbose_name='MNDBT (m)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='vĩ độ đập')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='kinh độ đập')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'hồ chứa',
                'verbose_name_plural': 'hồ chứa',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OperatingDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(blank=True, choices=[('not_exceed', 'Không vượt'), ('lower_to', 'Hạ về')], help_text='Để trống chỉ khi văn bản gốc không ghi rõ (dữ liệu ví dụ Phụ lục A.4).', max_length=12, verbose_name='loại yêu cầu')),
                ('target_level', models.FloatField(verbose_name='mực nước mục tiêu (m)')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='bắt đầu')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='hạn hoàn thành')),
                ('document', models.CharField(help_text='Số, ngày văn bản và cơ quan ban hành', max_length=255, verbose_name='văn bản')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='còn hiệu lực')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='nhập lúc')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='hết hiệu lực lúc')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='người đánh dấu')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='người nhập')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directives', to='reservoirs.reservoir', verbose_name='hồ')),
            ],
            options={
                'verbose_name': 'chỉ đạo điều hành',
                'verbose_name_plural': 'chỉ đạo điều hành',
                'ordering': ['-is_active', '-created_at', 'reservoir'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('max_before_flood', 'Mực nước cao nhất trước lũ'), ('min_flood_reception', 'Mực nước đón lũ thấp nhất')], max_length=24, verbose_name='loại ngưỡng')),
                ('start_day', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$', 'Dạng tháng-ngày, ví dụ 09-01.')], verbose_name='từ ngày (tháng-ngày)')),
                ('end_day', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$', 'Dạng tháng-ngày, ví dụ 09-01.')], verbose_name='đến ngày (tháng-ngày)')),
                ('value_low', models.FloatField(verbose_name='giá trị thấp (m)')),
                ('value_high', models.FloatField(verbose_name='giá trị cao (m)')),
                ('document', models.CharField(max_length=255, verbose_name='văn bản')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật lúc')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='reservoirs.reservoir', verbose_name='hồ')),
            ],
            options={
                'verbose_name': 'ngưỡng quy định',
                'verbose_name_plural': 'ngưỡng quy định',
                'ordering': ['reservoir', 'kind', 'start_day'],
                'constraints': [models.UniqueConstraint(fields=('reservoir', 'kind', 'start_day'), name='uniq_threshold_period'), models.CheckConstraint(condition=models.Q(('value_low__lte', models.F('value_high'))), name='threshold_low_lte_high')],
            },
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, verbose_name='thời điểm')),
                ('rain_mm', models.FloatField(verbose_name='mưa (mm)')),
                ('source', models.CharField(choices=[('historical', 'Open-Meteo Historical (archive)'), ('forecast', 'Open-Meteo Forecast (past_days)')], max_length=12, verbose_name='nguồn')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall', to='reservoirs.reservoir', verbose_name='hồ')),
            ],
            options={
                'verbose_name': 'lượng mưa',
                'verbose_name_plural': 'lượng mưa',
                'ordering': ['reservoir', 'time'],
                'constraints': [models.UniqueConstraint(fields=('reservoir', 'time'), name='uniq_rainfall')],
            },
        ),
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, verbose_name='thời điểm')),
                ('water_level', models.FloatField(blank=True, null=True, verbose_name='mực nước (m)')),
                ('inflow', models.FloatField(blank=True, null=True, verbose_name='lưu lượng đến (m³/s)')),
                ('turbine_flow', models.FloatField(blank=True, null=True, verbose_name='lưu lượng qua máy (m³/s)')),
                ('spillway_flow', models.FloatField(blank=True, null=True, verbose_name='lưu lượng qua tràn (m³/s)')),
                ('suspicious', models.BooleanField(default=False, help_text='Bị quy trình làm sạch lúc huấn luyện loại bỏ (ngoài phạm vi, loại trừ thủ công, gai), hoặc là giờ mới nhất mà du_bao() báo cần xác nhận.', verbose_name='nghi ngờ')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reservoirs.reservoir', verbose_name='hồ')),
            ],
            options={
                'verbose_name': 'số liệu vận hành',
                'verbose_name_plural': 'số liệu vận hành',
                'ordering': ['reservoir', 'time'],
                'constraints': [models.UniqueConstraint(fields=('reservoir', 'time'), name='uniq_operation_record')],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(db_index=True, help_text='Giờ của số liệu mới nhất đưa vào mô hình.', verbose_name='thời điểm dự báo')),
                ('horizon', models.PositiveSmallIntegerField(choices=[(1, '1 giờ'), (3, '3 giờ'), (6, '6 giờ')], verbose_name='tầm (giờ)')),
                ('expected_level', models.FloatField(blank=True, null=True, verbose_name='mực nước dự kiến (m)')),
                ('alert_level', models.CharField(blank=True, choices=[('normal', 'Bình thường'), ('watch', 'Theo dõi'), ('warning', 'Cảnh báo'), ('emergency', 'Khẩn cấp')], max_length=10, null=True, verbose_name='mức cảnh báo')),
                ('baseline_alert', models.BooleanField(blank=True, null=True, verbose_name='Baseline báo')),
                ('a_alert', models.BooleanField(blank=True, null=True, verbose_name='phương án A báo')),
                ('b_alert', models.BooleanField(blank=True, null=True, verbose_name='phương án B báo')),
                ('needs_confirmation', models.BooleanField(default=False, verbose_name='cần xác nhận dữ liệu')),
                ('model_version', models.CharField(max_length=40, verbose_name='phiên bản mô hình')),
                ('is_simulation', models.BooleanField(db_index=True, default=False, verbose_name='mô phỏng')),
                ('details', models.JSONField(default=dict, verbose_name='chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='tạo lúc')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='reservoirs.reservoir', verbose_name='hồ')),
            ],
            options={
                'verbose_name': 'kết quả dự báo',
                'verbose_name_plural': 'kết quả dự báo',
                'ordering': ['reservoir', '-issued_at', 'horizon'],
                'constraints': [models.UniqueConstraint(fields=('reservoir', 'issued_at', 'horizon', 'is_simulation'), name='uniq_forecast')],
            },
        ),
        migrations.CreateModel(
            name='ReservoirWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('dam_area', 'Khu vực đập'), ('near_downstream', 'Hạ du gần'), ('delta_downstream', 'Hạ du đồng bằng')], max_length=20, verbose_name='loại vùng')),
                ('needs_verification', models.BooleanField(default=False, help_text='Các xã đánh dấu (*) ở Phụ lục B: chưa chắc nằm phía trên hay phía dưới đập.', verbose_name='cần xác minh trên bản đồ')),
                ('reservoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_links', to='reservoirs.reservoir', verbose_name='hồ')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservoir_links', to='catalog.ward', verbose_name='phường/xã')),
            ],
            options={
                'verbose_name': 'liên kết hồ – phường/xã',
                'verbose_name_plural': 'liên kết hồ – phường/xã',
                'constraints': [models.UniqueConstraint(fields=('reservoir', 'ward'), name='uniq_reservoir_ward')],
            },
        ),
        migrations.CreateModel(
            name='UpdateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, verbose_name='lần chạy')),
                ('kind', models.CharField(choices=[('live', 'Cập nhật hằng giờ'), ('replay', 'Phát lại (mô phỏng)')], default='live', max_length=10, verbose_name='loại')),
                ('step', models.CharField(choices=[('reservoir_data', 'Dữ liệu hồ (cổng PCTT)'), ('rain_archive', 'Mưa Open-Meteo Historical'), ('rain_forecast', 'Mưa Open-Meteo Forecast'), ('suspicious_flags', 'Đánh dấu số liệu nghi ngờ'), ('forecast', 'Dự báo'), ('alerts', 'Cảnh báo và thông báo')], max_length=20, verbose_name='bước')),
                ('started_at', models.DateTimeField(verbose_name='bắt đầu')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='kết thúc')),
                ('success', models.BooleanField(default=False, verbose_name='thành công')),
                ('error', models.TextField(blank=True, verbose_name='lỗi')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='chi tiết')),
                ('reservoir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reservoirs.reservoir', verbose_name='hồ')),
            ],
            options={
                'verbose_name': 'lần cập nhật',
                'verbose_name_plural': 'lần cập nhật',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['step', '-started_at'], name='reservoirs__step_85f82b_idx')],
            },
        ),
    ]
