# Generated by Django 5.2.17 on 2026-10-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='thời điểm')),
                ('actor_label', models.CharField(blank=True, max_length=255, verbose_name='người thực hiện (lúc ghi)')),
                ('action', models.CharField(choices=[('login', 'Đăng nhập'), ('user_created', 'Tạo tài khoản'), ('user_updated', 'Sửa tài khoản'), ('user_locked', 'Khoá tài khoản'), ('user_unlocked', 'Mở khoá tài khoản'), ('role_changed', 'Đổi vai trò'), ('password_reset_by_admin', 'Admin đặt lại mật khẩu'), ('config_changed', 'Sửa cấu hình')], db_index=True, max_length=40, verbose_name='thao tác')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='loại đối tượng')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='mã đối tượng')),
                ('target_label', models.CharField(blank=True, max_length=255, verbose_name='đối tượng')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='chi tiết')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='địa chỉ IP')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='người thực hiện')),
            ],
            options={
                'verbose_name': 'nhật ký',
                'verbose_name_plural': 'nhật ký hệ thống',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('sos_self_claim_wait_minutes', 'sos_self_claim_wait_minutes'), ('sos_anonymize_days', 'sos_anonymize_days'), ('max_failed_logins', 'max_failed_logins'), ('login_lockout_minutes', 'login_lockout_minutes'), ('email_verification_ttl_hours', 'email_verification_ttl_hours'), ('password_reset_ttl_minutes', 'password_reset_ttl_minutes'), ('jwt_access_minutes', 'jwt_access_minutes'), ('jwt_refresh_days', 'jwt_refresh_days'), ('rapid_rise_threshold_m', 'rapid_rise_threshold_m'), ('suspicious_jump_threshold_m', 'suspicious_jump_threshold_m'), ('overview_refresh_minutes', 'overview_refresh_minutes'), ('dispatch_refresh_seconds', 'dispatch_refresh_seconds')], max_length=64, unique=True, verbose_name='khoá')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='giá trị')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='đơn vị')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='mô tả')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='cập nhật lúc')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='người cập nhật')),
            ],
            options={
                'verbose_name': 'tham số cấu hình',
                'verbose_name_plural': 'cấu hình hệ thống',
                'ordering': ['key'],
            },
        ),
    ]
