# Generated by Django 5.2.17 on 2026-10-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_audit_log_append_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Đăng nhập'), ('user_created', 'Tạo tài khoản'), ('user_updated', 'Sửa tài khoản'), ('user_locked', 'Khoá tài khoản'), ('user_unlocked', 'Mở khoá tài khoản'), ('role_changed', 'Đổi vai trò'), ('password_reset_by_admin', 'Admin đặt lại mật khẩu'), ('config_changed', 'Sửa cấu hình'), ('threshold_changed', 'Sửa ngưỡng quy định'), ('directive_created', 'Thêm chỉ đạo điều hành'), ('directive_deactivated', 'Đánh dấu chỉ đạo hết hiệu lực')], db_index=True, max_length=40, verbose_name='thao tác'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(choices=[('sos_self_claim_wait_minutes', 'sos_self_claim_wait_minutes'), ('sos_anonymize_days', 'sos_anonymize_days'), ('max_failed_logins', 'max_failed_logins'), ('login_lockout_minutes', 'login_lockout_minutes'), ('email_verification_ttl_hours', 'email_verification_ttl_hours'), ('password_reset_ttl_minutes', 'password_reset_ttl_minutes'), ('jwt_access_minutes', 'jwt_access_minutes'), ('jwt_refresh_days', 'jwt_refresh_days'), ('rapid_rise_threshold_m', 'rapid_rise_threshold_m'), ('suspicious_jump_threshold_m', 'suspicious_jump_threshold_m'), ('overview_refresh_minutes', 'overview_refresh_minutes'), ('stale_data_hours', 'stale_data_hours'), ('warning_reminder_hours', 'warning_reminder_hours'), ('auto_alert_valid_hours', 'auto_alert_valid_hours'), ('forecast_input_hours', 'forecast_input_hours'), ('history_max_days', 'history_max_days'), ('pctt_min_interval_minutes', 'pctt_min_interval_minutes'), ('rain_archive_lag_days', 'rain_archive_lag_days'), ('dispatch_refresh_seconds', 'dispatch_refresh_seconds')], max_length=64, unique=True, verbose_name='khoá'),
        ),
    ]
